version: "3.5"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  oauth2:
    links:
         - redis
    container_name: oauth2
    command: "node app.js --prod"

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "1347:1347"
    environment:
      - NODE_ENV=production
# networks:
#   redis-net:

# volumes:
#   redis-data:

# run multi env with file docker
# docker-compose -f docker-compose-prod.yml up -d --build

#run with env production
# docker build -f Dockerfile-prod -t veo-frontend-prod .
#  docker run -it -p 80:80 --rm veo-frontend
